[testServer]
BROKER_HOST = 100.95.216.119
BROKER_PORT = 5672
; annihilated user, pass, and vhost here so git doesn't track
EXCHANGE = mqExchange
QUEUE = testQueue
;EXCHANGE_TYPE = test
AUTO_DELETE = true

[loginServer]
BROKER_HOST = 100.95.216.119
BROKER_PORT = 5672
EXCHANGE = loginExchange
QUEUE = loginQueue

[registerServer]
BROKER_HOST = 100.95.216.119
BROKER_PORT = 5672
EXCHANGE = registerExchange
QUEUE = registerQueue
